; Listing generated by Microsoft (R) Optimizing Compiler Version 15.00.21022.08 

	TITLE	D:\Software\MSYS2\home\wurui\Assembly\code.c
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_accum
_BSS	SEGMENT
_accum	DD	01H DUP (?)
_BSS	ENDS
PUBLIC	_sum
; Function compile flags: /Odtp
_TEXT	SEGMENT
_t$ = -4						; size = 4
_x$ = 8							; size = 4
_y$ = 12						; size = 4
_sum	PROC
; File d:\software\msys2\home\wurui\assembly\code.c
; Line 3
	push	ebp
	mov	ebp, esp
	push	ecx
; Line 4
	mov	eax, DWORD PTR _x$[ebp]
	add	eax, DWORD PTR _y$[ebp]
	mov	DWORD PTR _t$[ebp], eax
; Line 5
	mov	ecx, DWORD PTR _accum
	add	ecx, DWORD PTR _t$[ebp]
	mov	DWORD PTR _accum, ecx
; Line 6
	mov	eax, DWORD PTR _t$[ebp]
; Line 7
	mov	esp, ebp
	pop	ebp
	ret	0
_sum	ENDP
_TEXT	ENDS
END
